In [80]:
import tensorflow as tf
import numpy as np
from tf_helpers import flatten

In [81]:
def mimic_filter_maps(x):
    """
    expand dimension to mimic batches of filter maps of shape (batch, height, width, channel)
    in this case, width=1, channel=1    
    """
    expanded = np.expand_dims(x, -1)
    expanded = np.expand_dims(expanded, -1)
    return expanded


In [82]:
# input to the algorithm
k = 2
x = mimic_filter_maps(np.array([[1, 2, 3, 4], [1, 2, 0, 0], [0, 3, 1, 2]]))
y = mimic_filter_maps(np.array([[3, 4], [1, 2], [3, 2]]))

In [86]:
x.shape

(3, 4, 1, 1)

In [83]:
sess = tf.InteractiveSession()
tf_x = tf.constant(x)
tf_y = tf.constant(y)

In [84]:
tf_x_squeezed = tf.squeeze(tf_x)
top_k_values, top_k_indices = tf.nn.top_k(tf_x_squeezed, k=2, sorted=False)
sorting_indices = tf.reverse(tf.nn.top_k(top_k_indices, k=top_k_indices.shape[1], sorted=True).indices, axis=[-1])
print('top_k_values\n', top_k_values.eval())
print('top_k_indices\n', top_k_indices.eval())
print('sorting_indices\n', sorting_indices.eval())


top_k_values
 [[3 4]
 [1 2]
 [2 3]]
top_k_indices
 [[2 3]
 [0 1]
 [3 1]]
sorting_indices
 [[0 1]
 [0 1]
 [1 0]]


In [85]:
flattened_indices = flatten(sorting_indices)
offset_short = tf.range(0, flattened_indices.shape[0], k)
offset_col = tf.expand_dims(offset_short, -1)  # to column
offset_flattened = tf.tile(offset_col, [1, k])  # repeat on each row
offset = flatten(offset_flattened)  # flatten it
offset.eval()
indices = offset + flattened_indices

flattened_values = flatten(top_k_values)
reindexed_values_flattened = tf.gather(flattened_values, indices)
reindexed_values = tf.reshape(reindexed_values_flattened, [-1, k])
print(reindexed_values.eval())

[[3 4]
 [1 2]
 [3 2]]


In [ ]:
tf.reshape(sorting_indices

In [12]:
top_k_values, top_k_indices = sess.run([top_k_values, top_k_indices])
print(top_k_values)
print(top_k_indices)

NameError: name 'top_k_values_t' is not defined

In [13]:
tf.gather?

In [20]:
tf.gather([[1,2,3], [2,3,4], [4,5,6]], [[1, 2], [0, 1]], axis=-1).eval()

array([[[2, 3],
        [1, 2]],

       [[3, 4],
        [2, 3]],

       [[5, 6],
        [4, 5]]], dtype=int32)