In [1]:
# demo on how to slice a tensor in tensorflow

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
a = np.arange(10).reshape(5, 2)

In [4]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
v = tf.constant(a)
indices = tf.placeholder(dtype=tf.int32)

In [6]:
sub_v = tf.gather(v, indices)

In [7]:
sess = tf.InteractiveSession()

In [8]:
output = sess.run(sub_v, feed_dict={indices: [2,3,1]})

In [9]:
output

array([[4, 5],
       [6, 7],
       [2, 3]])

In [10]:
a[[2,3,1]]

array([[4, 5],
       [6, 7],
       [2, 3]])

In [11]:
assert (a[[2,3,1]] == output).all()